### ISSUE TITLE
error[E0428]

### ISSUE THREAD

**Issue by iwu2us** [agmmnn/tauri-ui#2]
error[E0428]: the name `ERROR_CTX_GRAPHICS_INVALID` is defined multiple times
    --> C:\Users\alvin\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.9\src\shared\winerror.rs:1803:1
     |
1802 | pub const ERROR_CTX_GRAPHICS_INVALID: DWORD = 7035;
     | ------------------------------------------- previous definition of the value `ERROR_CTX_GRAPHICS_INVALID` here
1803 | pub const ERROR_CTX_LOGON_DISABLED: DWORD = 7037;
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `ERROR_CTX_GRAPHICS_INVALID` redefined here
     |
     = note: `ERROR_CTX_GRAPHICS_INVALID` must be defined only once in the value namespace of this module

   Compiling serde_urlencoded v0.7.1
For more information about this error, try `rustc --explain E0428`.
error: could not compile `winreg` due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by agmmnn** [comment]
it can be releated with https://github.com/retep998/winapi-rs or tauri, what is your system specs is it win32?

**Comment by iwu2us** [comment]
Solven, i ran again pnp tauri dev and works.
