### ISSUE TITLE
installation issues on mac(intel)

### ISSUE THREAD

**Issue by SaraiQX** [agmmnn/tauri-ui#7]
Dear team, 
Thanks for this work.
Just found the command cannot work well when I tried to initiate the project. Thanks in advance.
```

saraiqx@saraiqxdeMacBook-Pro sveltekit % npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tauri-ui-svelte@0.1.0
npm ERR! Found: svelte@4.1.2
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^4.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^3.49.0" from @tanstack/svelte-table@8.9.4
npm ERR! node_modules/@tanstack/svelte-table
npm ERR!   @tanstack/svelte-table@"^8.9.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by agmmnn** [comment]
Hey,

The main package manager of the repo is **pnpm**. I suggest you use **pnpm**, It seems like you're encountering a dependency resolution issue when trying to install dependencies for your project using **npm**. If you want to continue with **npm**, you can try this:

	npm install --legacy-peer-deps

References:
https://stackoverflow.com/a/76249649/5909073
https://stackoverflow.com/a/75231748/5909073
