### ISSUE TITLE
Window freezes after fresh tauri-ui installation with Vite + React

### ISSUE THREAD

**Issue by ThibaultDct** [agmmnn/tauri-ui#9]
Hello,
First, nice job on your templates.
I currently have an issue starting my application using tauri-ui just after initialization.

I successfully ran pnpm install, no issue 

But when I try to run pnpm tauri dev, the application window appears, but freezes instantly, without giving any stack trace or error. I only can force close the application.

Any guess ? Thank you!

**Comment by ThibaultDct** [comment]
Some info :
- OS : MacOS (ARM) Ventura 13.5
- pnpm 8.6.12
- rustc 1.71.1
- @tauri-apps/api: 2.0.0-alpha.5
- @tauri-apps/plugin-app: 2.0.0-alpha.0
- @tauri-apps/plugin-os: 2.0.0-alpha.0
- @tauri-apps/plugin-shell: 2.0.0-alpha.0
- @tauri-apps/plugin-window: 2.0.0-alpha.0
- react 18.2.0
- vite 4.4.8

**Comment by rejochandran** [comment]
+1

**Comment by drixie** [comment]
+1

**Comment by drixie** [comment]
Might be a good idea to create the package with the stable versions rather than alpha

**Comment by wanghaisheng** [comment]
anyone fix this, I seem to encounter this vite template issue on my macmini

**Comment by clementroure** [comment]
same on my MacBook Air m2

**Comment by nhathoang1bit** [comment]
Same issue on Macbook M1 Pro

**Comment by agmmnn** [comment]
At the moment I'm a little busy, but I'll update the repo soon to match the latest Tauri release. 🙏
